# Generated by Django 2.2 on 2020-08-07 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=13, verbose_name='RUC')),
                ('nombre', models.CharField(max_length=300, verbose_name='Nombres')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('precio', models.FloatField(default=0, verbose_name='Precio')),
                ('stock', models.FloatField(default=0, verbose_name='Stock')),
                ('iva', models.BooleanField(default=True, verbose_name='IVA')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de venta')),
                ('total', models.FloatField(default=0, verbose_name='Total')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Cliente', verbose_name='Seleccione el cliente')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0, verbose_name='Cantidad')),
                ('precio', models.FloatField(default=0, verbose_name='Precio')),
                ('subtotal', models.FloatField(default=0, verbose_name='Subtotal')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Factura', verbose_name='Seleccione la factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Producto', verbose_name='Seleccione el producto')),
            ],
            options={
                'verbose_name': 'DetalleFactura',
                'verbose_name_plural': 'DetalleFacturas',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='producto',
            field=models.ManyToManyField(to='mainapp.Producto', verbose_name='Seleccione el producto'),
        ),
    ]
